/**
 * OptimizePress3 element
 */
;(function($, window, document) {

    "use strict";

    /**
     * OP3_Element constructor
     *
     * @param {Class}
     */
    OP3.Elements._extension.type.WebinarCalendar = OP3.defineClass({

        Name: "OP3.Element.WebinarCalendar",

        Extends: OP3.Elements._extension.type.Default,

        Constructor: function(arg) {
            return OP3.Elements._extension.type.Default.apply(this, arguments);
        },

        Prototype: {

            _type: "webinarcalendar",

            _props: function() {
                return [

                    [ OP3.Elements._extension.prop.BoxModel ],
                    [ OP3.Elements._extension.prop.MarginTop ],
                    [ OP3.Elements._extension.prop.MarginBottom ],
                    [ OP3.Elements._extension.prop.MarginLeft ],
                    [ OP3.Elements._extension.prop.MarginRight ],
                    [ OP3.Elements._extension.prop.PaddingTop ],
                    [ OP3.Elements._extension.prop.PaddingBottom ],
                    [ OP3.Elements._extension.prop.PaddingLeft ],
                    [ OP3.Elements._extension.prop.PaddingRight ],
                    [ OP3.Elements._extension.prop.PaddingDrag ],
                    [ OP3.Elements._extension.prop.MarginAlign ],
                    [ OP3.Elements._extension.prop.MaxWidth ],

                    [ OP3.Elements._extension.prop.Display, { id: "displayDeviceVisibility" } ],
                    [ OP3.Elements._extension.prop.DeviceVisibility, { label: OP3._("Element Visible On") } ],
                    [ OP3.Elements._extension.prop.ForceVisibility ],

                    // Advanced Tab - Animation & Delay
                    [ OP3.Elements._extension.prop.AnimationTrigger ],
                    [ OP3.Elements._extension.prop.AnimationStyle ],
                    [ OP3.Elements._extension.prop.AnimationLoop ],
                    [ OP3.Elements._extension.prop.TimerMinutes ],
                    [ OP3.Elements._extension.prop.TimerSeconds ],

                    [ OP3.Elements._extension.prop.Id ],
                    [ OP3.Elements._extension.prop.Uuid ],
                    [ OP3.Elements._extension.prop.Caption ],
                    [ OP3.Elements._extension.prop.Class ],
                    [ OP3.Elements._extension.prop.LinkProperties ],
                    [ OP3.Elements._extension.prop.ZIndex ],
                    [ OP3.Elements._extension.prop.CodeBeforeElement ],
                    [ OP3.Elements._extension.prop.CodeAfterElement ],

                    [ OP3.Elements._extension.prop.Gutter, { label: OP3._("Calendar Item Spacing") } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "gutterLeft", label: OP3._("Gutter Left"), selector: ' [data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "gutterRight", label: OP3._("Gutter Right"), selector: ' [data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "gutterAdjustLeft", label: OP3._("Gutter Adjust Left"), selector: ' > [data-op3-element-container] > [data-op3-children]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "gutterAdjustRight", label: OP3._("Gutter Adjust Right"), selector: ' > [data-op3-element-container] > [data-op3-children]' } ],

                    // Link properties - webinarCalendarItem
                    [ OP3.Elements._extension.prop.Height, { id: "webinarCalendarItemHeight", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] svg' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "webinarCalendarItemBackgroundImageBase", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::before, .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "webinarCalendarItemBackgroundColorBase", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::before, .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "webinarCalendarItemBorderTopWidth", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "webinarCalendarItemBorderTopStyle", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "webinarCalendarItemBorderTopColor", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "webinarCalendarItemBorderRightWidth", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "webinarCalendarItemBorderRightStyle", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "webinarCalendarItemBorderRightColor", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "webinarCalendarItemBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "webinarCalendarItemBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "webinarCalendarItemBorderBottomColor", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "webinarCalendarItemBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "webinarCalendarItemBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "webinarCalendarItemBorderLeftColor", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "webinarCalendarItemBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "webinarCalendarItemBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "webinarCalendarItemBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "webinarCalendarItemBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "webinarCalendarItemBoxShadow", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "webinarCalendarItemMarginTop", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "webinarCalendarItemMarginBottom", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "webinarCalendarItemMarginLeft", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "webinarCalendarItemMarginRight", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "webinarCalendarItemPaddingTop", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "webinarCalendarItemPaddingBottom", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "webinarCalendarItemPaddingLeft", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "webinarCalendarItemPaddingRight", selector: ' .op3-element[data-op3-element-type="webinarcalendaritem"]' } ],

                    // Link Properties - text
                    [ OP3.Elements._extension.prop.FontFamily, { id: "textFontFamily", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "textColor", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "textFontSize", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "textLineHeight", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "textLetterSpacing", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "textFontWeight", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "textFontStyle", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "textTextTransform", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "textTextDecoration", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "textTextAlign", selector: ' .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "textBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "textMarginTop", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "textMarginBottom", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "textMarginLeft", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "textMarginRight", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "textPaddingTop", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "textPaddingBottom", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "textPaddingLeft", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "textPaddingRight", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "textMaxWidth", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "textBorderTopWidth", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "textBorderTopStyle", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "textBorderTopColor", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "textBorderRightWidth", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "textBorderRightStyle", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "textBorderRightColor", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "textBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "textBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "textBorderBottomColor", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "textBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "textBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "textBorderLeftColor", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "textBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "textBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "textBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "textBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="text"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "textDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-type="text"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "textTransitionDuration", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "textColorHover", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "textFontWeightHover", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "textFontStyleHover", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "textTextTransformHover", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "textTextDecorationHover", selector: ' .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-type="text"]:hover [data-op3-contenteditable] > ul' } ],
                ];

            },

        },

    });

})(jQuery, window, document);
