/**
 * OptimizePress3 element
 */
;(function($, window, document) {

    "use strict";

    /**
     * OP3_Element constructor
     *
     * @param {Class}
     */
    OP3.Elements._extension.type.OneTimeOffer = OP3.defineClass({

        Name: "OP3.Element.OneTimeOffer",

        Extends: OP3.Elements._extension.type.Default,

        Constructor: function(arg) {
            return OP3.Elements._extension.type.Default.apply(this, arguments);
        },

        Prototype: {

            _type: "onetimeoffer",

            _props: function() {
                return [
                    [ OP3.Elements._extension.prop.ProductId, { selector: ' [name="oto_product_id[]"]', attr: { "data-property-type": "onetimeoffer" } } ],
                    [ OP3.Elements._extension.prop.ProductSetupSource ],
                    [ OP3.Elements._extension.prop.CartPostAction, { selector: ' [name="oto-post-action"]' } ],
                    [ OP3.Elements._extension.prop.CartPostActionRedirectURL, { selector: ' [name="oto-post-action-redirect-url"]' } ],
                    [ OP3.Elements._extension.prop.CartPostActionFunnelStep, { selector: ' [name="oto-post-action-funnel-step"]' } ],
                    [ OP3.Elements._extension.prop.EditFinishText, { id: "editPaymentInputs", label: "Edit Payment Inputs", selector: " .opc-onetimeoffer" } ],

                    // Style tab - Background - Base
                    [ OP3.Elements._extension.prop.BackgroundImageType, { id: "backgroundImageBaseType", label: OP3._("Type"), options: [ { "none": "Background Colour" }, { "linear-gradient": "Linear Gradient" }, { "radial-gradient": "Radial Gradient" } ] } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "backgroundImageBase", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "backgroundColorBase", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImageAngle, { id: "backgroundImageBaseAngle" } ],
                    [ OP3.Elements._extension.prop.BackgroundImagePosition, { id: "backgroundImageBasePosition" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartColor, { id: "backgroundImageBaseStartColor" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartPosition, { id: "backgroundImageBaseStartPosition" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopColor, { id: "backgroundImageBaseStopColor" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopPosition, { id: "backgroundImageBaseStopPosition" } ],
                    // Style tab - Background - Background Image
                    [ OP3.Elements._extension.prop.BackgroundImage, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "backgroundImageDisplay", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundImageUrl ],
                    [ OP3.Elements._extension.prop.Opacity, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.Opacity100 ],
                    [ OP3.Elements._extension.prop.BackgroundPosition, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundAttachment, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundRepeat, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundSize, { selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    // Style tab - Background - Overlay
                    [ OP3.Elements._extension.prop.BackgroundImageType, { id: "backgroundImageOverlayType", label: OP3._("Overlay Type"), options: [ { "none": "Background Colour" }, { "linear-gradient": "Linear Gradient" }, { "radial-gradient": "Radial Gradient" } ] } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "backgroundImageOverlay", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "backgroundColorOverlay", label: OP3._("Overlay Background Color"), selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImageAngle, { id: "backgroundImageOverlayAngle", label: OP3._("Overlay Angle") } ],
                    [ OP3.Elements._extension.prop.BackgroundImagePosition, { id: "backgroundImageOverlayPosition", label: OP3._("Overlay Position") } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartColor, { id: "backgroundImageOverlayStartColor", label: OP3._("Overlay Start Color") } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartPosition, { id: "backgroundImageOverlayStartPosition", label: OP3._("Overlay Start Position") } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopColor, { id: "backgroundImageOverlayStopColor", label: OP3._("Overlay Stop Color") } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopPosition, { id: "backgroundImageOverlayStopPosition", label: OP3._("Overlay Stop Position") } ],

                    // Style tab - Border
                    [ OP3.Elements._extension.prop.BorderTopWidth, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { selector: " > [data-op3-element-container] > [data-op3-border], > [data-op3-element-container]" } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BoxShadowAngle ],
                    [ OP3.Elements._extension.prop.BoxShadowDistance ],
                    [ OP3.Elements._extension.prop.BoxShadowBlur ],
                    [ OP3.Elements._extension.prop.BoxShadowSpread ],
                    [ OP3.Elements._extension.prop.BoxShadowColor ],
                    // [ OP3.Elements._extension.prop.BoxShadowInset ],

                    // Advanced Tab - Positioning
                    [ OP3.Elements._extension.prop.BoxModel ],
                    [ OP3.Elements._extension.prop.MarginTop ],
                    [ OP3.Elements._extension.prop.MarginBottom ],
                    [ OP3.Elements._extension.prop.MarginLeft ],
                    [ OP3.Elements._extension.prop.MarginRight ],
                    [ OP3.Elements._extension.prop.PaddingTop ],
                    [ OP3.Elements._extension.prop.PaddingBottom ],
                    [ OP3.Elements._extension.prop.PaddingLeft ],
                    [ OP3.Elements._extension.prop.PaddingRight ],
                    [ OP3.Elements._extension.prop.PaddingDrag ],
                    [ OP3.Elements._extension.prop.MarginAlign ],
                    [ OP3.Elements._extension.prop.Width ],

                    // Sidebar: Advanced Tab - Responsive
                    [ OP3.Elements._extension.prop.Display, { id: "displayDeviceVisibility" } ],
                    [ OP3.Elements._extension.prop.DeviceVisibility, { label: OP3._("Element Visible On") } ],
                    [ OP3.Elements._extension.prop.ForceVisibility ],

                    // Advanced Tab - Animation & Delay
                    [ OP3.Elements._extension.prop.AnimationTrigger ],
                    [ OP3.Elements._extension.prop.AnimationStyle ],
                    [ OP3.Elements._extension.prop.AnimationLoop ],
                    [ OP3.Elements._extension.prop.TimerMinutes ],
                    [ OP3.Elements._extension.prop.TimerSeconds ],

                    // Advanced Tab - Advanced
                    [ OP3.Elements._extension.prop.Id ],
                    [ OP3.Elements._extension.prop.Uuid ],
                    [ OP3.Elements._extension.prop.Caption ],
                    [ OP3.Elements._extension.prop.Class ],
                    [ OP3.Elements._extension.prop.LinkProperties ],
                    [ OP3.Elements._extension.prop.ZIndex ],
                    [ OP3.Elements._extension.prop.CodeBeforeElement ],
                    [ OP3.Elements._extension.prop.CodeAfterElement ],

                    // Properties - Used For Presets - Button (Upsell)
                    [ OP3.Elements._extension.prop.Color, { id: "buttonColor", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "buttonMaxWidth", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.Height, { id: "buttonHeight", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "buttonBackgroundImageOverlay", selector: ' .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "buttonBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.FontFamily, { id: "buttonFontFamily", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonFontSize", selector: ' .op3-element[data-op3-element-spec="button"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "buttonLineHeight", selector: ' .op3-element[data-op3-element-spec="button"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "buttonLetterSpacing", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "buttonFontWeight", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "buttonFontStyle", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "buttonTextTransform", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "buttonTextDecoration", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.AlignItems, { id: "buttonButtonAlignText", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "buttonButtonTextAlign", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonSubtextDisplay", selector: ' .op3-element[data-op3-element-spec="button"] .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "buttonFontWeightSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "buttonFontStyleSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "buttonTextTransformSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "buttonTextDecorationSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonFontSizeSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "buttonLetterSpacingSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonOffsetXSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "buttonOffsetYSubtext", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonDisplay", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.Op3Icon, { id: "buttonOp3Icon", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonIconColor", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonIconSize", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FlexDirection, { id: "buttonIconDirection", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.Width, { id: "buttonIconSpacing", selector: ' .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "buttonBorderTopWidth", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "buttonBorderTopStyle", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "buttonBorderTopColor", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "buttonBorderRightWidth", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "buttonBorderRightStyle", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "buttonBorderRightColor", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "buttonBorderBottomWidth", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "buttonBorderBottomStyle", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "buttonBorderBottomColor", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "buttonBorderLeftWidth", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "buttonBorderLeftStyle", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "buttonBorderLeftColor", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "buttonBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "buttonBorderTopRightRadius", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "buttonBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "buttonBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadow", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadowInset", selector: ' .op3-element[data-op3-element-spec="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.TextShadow, { id: "buttonTextShadow", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "buttonMarginTop", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "buttonMarginBottom", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonMarginLeft", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "buttonMarginRight", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "buttonPaddingTop", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "buttonPaddingBottom", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "buttonPaddingLeft", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "buttonPaddingRight", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonHorizontalSpacingLeft", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "buttonHorizontalSpacingRight", selector: ' .op3-element[data-op3-element-spec="button"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-spec="button"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "buttonTransitionDuration", selector: ' .op3-element[data-op3-element-spec="button"] > a, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Filter, { id: "buttonFilterHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonColorHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonIconColorHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover > .op3-text-container > i' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "buttonBackgroundImageOverlayHover", selector: ' .op3-element[data-op3-element-spec="button"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "buttonBackgroundColorOverlayHover", selector: ' .op3-element[data-op3-element-spec="button"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "buttonBorderTopWidthHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "buttonBorderTopStyleHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "buttonBorderTopColorHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "buttonBorderRightWidthHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "buttonBorderRightStyleHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "buttonBorderRightColorHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "buttonBorderBottomWidthHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "buttonBorderBottomStyleHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "buttonBorderBottomColorHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "buttonBorderLeftWidthHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "buttonBorderLeftStyleHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "buttonBorderLeftColorHover" , selector: ' .op3-element[data-op3-element-spec="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "buttonBorderTopLeftRadiusHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "buttonBorderTopRightRadiusHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "buttonBorderBottomRightRadiusHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "buttonBorderBottomLeftRadiusHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadowHover", selector: ' .op3-element[data-op3-element-spec="button"] > a:hover' } ],

                    // Properties - Used For Presets - Button (Downsell)
                    [ OP3.Elements._extension.prop.Color, { id: "downsellColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "downsellMaxWidth", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.Height, { id: "downsellHeight", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "downsellBackgroundImageOverlay", selector: ' .op3-element[data-op3-element-spec="downsell"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "downsellBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-spec="downsell"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-spec="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.FontFamily, { id: "downsellFontFamily", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "downsellFontSize", selector: ' .op3-element[data-op3-element-spec="downsell"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "downsellLineHeight", selector: ' .op3-element[data-op3-element-spec="downsell"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "downsellLetterSpacing", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "downsellFontWeight", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "downsellFontStyle", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "downsellTextTransform", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "downsellTextDecoration", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.AlignItems, { id: "downsellButtonAlignText", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "downsellButtonTextAlign", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "downsellSubtextDisplay", selector: ' .op3-element[data-op3-element-spec="downsell"] .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "downsellFontWeightSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "downsellFontStyleSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "downsellTextTransformSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "downsellTextDecorationSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "downsellFontSizeSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "downsellLetterSpacingSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "downsellOffsetXSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "downsellOffsetYSubtext", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "downsellDisplay", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.Op3Icon, { id: "downsellOp3Icon", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "downsellIconColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "downsellIconSize", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FlexDirection, { id: "downsellIconDirection", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.Width, { id: "downsellIconSpacing", selector: ' .op3-element[data-op3-element-spec="downsell"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "downsellBorderTopWidth", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "downsellBorderTopStyle", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "downsellBorderTopColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "downsellBorderRightWidth", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "downsellBorderRightStyle", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "downsellBorderRightColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "downsellBorderBottomWidth", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "downsellBorderBottomStyle", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "downsellBorderBottomColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "downsellBorderLeftWidth", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "downsellBorderLeftStyle", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "downsellBorderLeftColor", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "downsellBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "downsellBorderTopRightRadius", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "downsellBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "downsellBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "downsellBoxShadow", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "downsellBoxShadowInset", selector: ' .op3-element[data-op3-element-spec="downsell"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.TextShadow, { id: "downsellTextShadow", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "downsellMarginTop", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "downsellMarginBottom", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "downsellMarginLeft", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "downsellMarginRight", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "downsellPaddingTop", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "downsellPaddingBottom", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "downsellPaddingLeft", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "downsellPaddingRight", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "downsellHorizontalSpacingLeft", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "downsellHorizontalSpacingRight", selector: ' .op3-element[data-op3-element-spec="downsell"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "downsellDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-spec="downsell"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "downsellTransitionDuration", selector: ' .op3-element[data-op3-element-spec="downsell"] > a, .op3-element[data-op3-element-spec="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Filter, { id: "downsellFilterHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "downsellColorHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "downsellIconColorHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover > .op3-text-container > i' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "downsellBackgroundImageOverlayHover", selector: ' .op3-element[data-op3-element-spec="downsell"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "downsellBackgroundColorOverlayHover", selector: ' .op3-element[data-op3-element-spec="downsell"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "downsellBorderTopWidthHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "downsellBorderTopStyleHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "downsellBorderTopColorHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "downsellBorderRightWidthHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "downsellBorderRightStyleHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "downsellBorderRightColorHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "downsellBorderBottomWidthHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "downsellBorderBottomStyleHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "downsellBorderBottomColorHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "downsellBorderLeftWidthHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "downsellBorderLeftStyleHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "downsellBorderLeftColorHover" , selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "downsellBorderTopLeftRadiusHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "downsellBorderTopRightRadiusHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "downsellBorderBottomRightRadiusHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "downsellBorderBottomLeftRadiusHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "downsellBoxShadowHover", selector: ' .op3-element[data-op3-element-spec="downsell"] > a:hover' } ],
                ];
            },

        },

    });

    // Open cart wizard on element drop
    OP3.bind("elementdrop::onetimeoffer", function(e, o) {
        if (typeof o.source !== "string" || !o.source.match(/^<_onetimeoffer_template\W/))
            return;

        OP3.once("elementfocus::onetimeoffer", function() {
            OP3.OneTimeOffer.openWizard();
        });
    });

})(jQuery, window, document);
