/**
 * OptimizePress3 element
 */
;(function($, window, document) {

    "use strict";

    /**
     * OP3_Element constructor
     *
     * @param {Class}
     */
    OP3.Elements._extension.type.CartSummary = OP3.defineClass({

        Name: "OP3.Element.CartSummary",

        Extends: OP3.Elements._extension.type.Default,

        Constructor: function(arg) {
            return OP3.Elements._extension.type.Default.apply(this, arguments);
        },

        Prototype: {

            _type: "cartsummary",

            _props: function() {
                return [
                    [ OP3.Elements._extension.prop.ToggleStatusError, { label: OP3._("Edit Status Message") } ],

                    // Sidebar: Advanced Tab - Positioning
                    [ OP3.Elements._extension.prop.BoxModel ],
                    [ OP3.Elements._extension.prop.MarginTop ],
                    [ OP3.Elements._extension.prop.MarginBottom ],
                    [ OP3.Elements._extension.prop.MarginLeft ],
                    [ OP3.Elements._extension.prop.MarginRight ],
                    [ OP3.Elements._extension.prop.PaddingTop ],
                    [ OP3.Elements._extension.prop.PaddingBottom ],
                    [ OP3.Elements._extension.prop.PaddingLeft ],
                    [ OP3.Elements._extension.prop.PaddingRight ],
                    [ OP3.Elements._extension.prop.PaddingDrag ],
                    [ OP3.Elements._extension.prop.MarginAlign ],
                    [ OP3.Elements._extension.prop.MaxWidth ],

                    // Sidebar: Advanced Tab - Responsive
                    [ OP3.Elements._extension.prop.Display, { id: "displayDeviceVisibility" } ],
                    [ OP3.Elements._extension.prop.DeviceVisibility, { label: OP3._("Element Visible On") } ],
                    [ OP3.Elements._extension.prop.ForceVisibility ],

                    // Sidebar: Advanced Tab - Advanced
                    [ OP3.Elements._extension.prop.Id ],
                    [ OP3.Elements._extension.prop.Uuid ],
                    [ OP3.Elements._extension.prop.Caption ],
                    [ OP3.Elements._extension.prop.Class ],
                    [ OP3.Elements._extension.prop.LinkProperties ],
                    [ OP3.Elements._extension.prop.ZIndex ],
                    [ OP3.Elements._extension.prop.CodeBeforeElement ],
                    [ OP3.Elements._extension.prop.CodeAfterElement ],

                    // Toolbar: Color Options
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "backgroundImageOverlay", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImageType, { id: "backgroundImageOverlayType", label: OP3._("Type"), options: [ { "none": "Background Colour" }, { "linear-gradient": "Linear Gradient" }, { "radial-gradient": "Radial Gradient" } ] } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "backgroundColorOverlay", selector: ' > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before, > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImageAngle, { id: "backgroundImageOverlayAngle" } ],
                    [ OP3.Elements._extension.prop.BackgroundImagePosition, { id: "backgroundImageOverlayPosition" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartColor, { id: "backgroundImageOverlayStartColor" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStartPosition, { id: "backgroundImageOverlayStartPosition" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopColor, { id: "backgroundImageOverlayStopColor" } ],
                    [ OP3.Elements._extension.prop.BackgroundImageStopPosition, { id: "backgroundImageOverlayStopPosition" } ],

                    // Toolbar: Borders & Corners
                    [ OP3.Elements._extension.prop.BorderTopWidth, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { selector: " > [data-op3-element-container], > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { selector: " > [data-op3-element-container] > [data-op3-border]" } ],
                    [ OP3.Elements._extension.prop.BoxShadowAngle ],
                    [ OP3.Elements._extension.prop.BoxShadowDistance ],
                    [ OP3.Elements._extension.prop.BoxShadowBlur ],
                    [ OP3.Elements._extension.prop.BoxShadowSpread ],
                    [ OP3.Elements._extension.prop.BoxShadowColor ],
                    // [ OP3.Elements._extension.prop.BoxShadowInset ],

                    // Link Properties - Headline
                    [ OP3.Elements._extension.prop.FontFamily, { id: "titleFontFamily", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "titleColor", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "titleFontSize", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "titleLineHeight", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "titleLetterSpacing", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "titleFontWeight", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "titleFontStyle", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "titleTextTransform", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "titleTextDecoration", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "titleTextAlign", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextShadow, { id: "titleTextShadow", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "titleBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "titleMarginTop", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "titleMarginBottom", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "titleMarginLeft", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "titleMarginRight", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "titlePaddingTop", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "titlePaddingBottom", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "titlePaddingLeft", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "titlePaddingRight", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "titleMaxWidth", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "titleBorderTopWidth", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "titleBorderTopStyle", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "titleBorderTopColor", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "titleBorderRightWidth", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "titleBorderRightStyle", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "titleBorderRightColor", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "titleBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "titleBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "titleBorderBottomColor", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "titleBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "titleBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "titleBorderLeftColor", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "titleBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "titleBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "titleBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "titleBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) .op3-headline-wrapper' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "titleDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"])' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "titleTransitionDuration", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "titleColorHover", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "titleFontWeightHover", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "titleFontStyleHover", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "titleTextTransformHover", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "titleTextDecorationHover", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]):hover [data-op3-contenteditable] > h6' } ],
                    [ OP3.Elements._extension.prop.Tag, { id: "titleTag", selector: ' .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h1, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h2, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h3, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h4, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h5, .op3-element[data-op3-element-type="headline"]:not([data-op3-element-spec="togglestatuserror"]) [data-op3-contenteditable] > h6' } ],

                    // Link properties - descriptionlist
                    [ OP3.Elements._extension.prop.MarginTop, { id: "descriptionListMarginTop", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "descriptionListMarginBottom", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "descriptionListMarginLeft", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "descriptionListMarginRight", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "descriptionListPaddingTop", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "descriptionListPaddingBottom", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "descriptionListPaddingLeft", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "descriptionListPaddingRight", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.Width, { id: "descriptionListWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "descriptionListDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-type="descriptionlist"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "descriptionListBackgroundImageOverlay", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before,  .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "descriptionListBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::before,  .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "descriptionListBorderTopWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "descriptionListBorderTopStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "descriptionListBorderTopColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "descriptionListBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "descriptionListBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "descriptionListBorderBottomColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "descriptionListRightTopWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "descriptionListRightTopStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "descriptionListRightTopColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "descriptionListLeftTopWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "descriptionListLeftTopStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "descriptionListLeftTopColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "descriptionListBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "descriptionListBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "descriptionListBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "descriptionListBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "descriptionListBoxShadow", selector: ' .op3-element[data-op3-element-type="descriptionlist"] > [data-op3-element-container] > [data-op3-border]' } ],

                    // Link Properties - descriptionlistitem
                    [ OP3.Elements._extension.prop.FontSize, { id: "descriptionListDescriptionListItemFontSize", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "descriptionListDescriptionListItemFontWeight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.FontFamily, { id: "descriptionListDescriptionListItemFontFamily", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "descriptionListDescriptionListItemFontStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "descriptionListDescriptionListItemLineHeight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "descriptionListDescriptionListItemLetterSpacing", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "descriptionListDescriptionListItemTextTransform", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "descriptionListDescriptionListItemTextDecoration", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "descriptionListDescriptionListItemValueFontSize", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "descriptionListDescriptionListItemValueFontWeight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.FontFamily, { id: "descriptionListDescriptionListItemValueFontFamily", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "descriptionListDescriptionListItemValueFontStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "descriptionListDescriptionListItemValueLineHeight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "descriptionListDescriptionListItemValueLetterSpacing", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "descriptionListDescriptionListItemValueTextTransform", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "descriptionListDescriptionListItemValueTextDecoration", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "descriptionListDescriptionListItemColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "descriptionListDescriptionListItemValueColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "descriptionListDescriptionListItemBackgroundColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "descriptionListDescriptionListItemBorderTopWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "descriptionListDescriptionListItemBorderTopStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "descriptionListDescriptionListItemBorderTopColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "descriptionListDescriptionListItemBorderRightWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "descriptionListDescriptionListItemBorderRightStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "descriptionListDescriptionListItemBorderRightColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "descriptionListDescriptionListItemBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "descriptionListDescriptionListItemBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "descriptionListDescriptionListItemBorderBottomColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "descriptionListDescriptionListItemBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "descriptionListDescriptionListItemBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container], .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "descriptionListDescriptionListItemBorderLeftColor", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "descriptionListDescriptionListItemBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "descriptionListDescriptionListItemBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "descriptionListDescriptionListItemBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "descriptionListDescriptionListItemBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] > [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "descriptionListDescriptionListItemMarginTop", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "descriptionListDescriptionListItemMarginBottom", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "descriptionListDescriptionListItemMarginLeft", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "descriptionListDescriptionListItemMarginRight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "descriptionListDescriptionListItemPaddingTop", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "descriptionListDescriptionListItemPaddingBottom", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "descriptionListDescriptionListItemPaddingLeft", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "descriptionListDescriptionListItemPaddingRight", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingDrag, { id: "descriptionListDescriptionListItemPaddingDrag", selector: ' .op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"]' } ],
                ];
            },
        },

    });

    // Set summary values readonly in LiveEditor
    OP3.bind("ready elementappend", function(e, o) {
        var parent = "cartsummary",
            children = [
                '.op3-element[data-op3-element-type="descriptionlist"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-value [data-op3-contenteditable]',
                '.op3-element[data-op3-element-spec="address"] .op3-element[data-op3-element-type="descriptionlistitem"] .op3-descriptionlistitem-key [data-op3-contenteditable]',
                '.op3-element[data-op3-element-spec="togglestatuserror"] [data-op3-contenteditable]',
            ],
            element = OP3.$(null);
        if (o && o.node)
            element = OP3.$(o.node);
        else
            element = OP3.$(parent);
        if (element.type() !== parent)
            element = element.find(parent);

        // no need to edit values
        // will be handled by opc plugin on frontend
        element
            .jq()
            .find(children.join(","))
            .each(function() {
               if (this.ice)
                    this.ice.destroy();
            });
    });

})(jQuery, window, document);
