/**
 * OptimizePress3 element
 */
;(function($, window, document) {

    "use strict";

    /**
     * OP3_Element constructor
     *
     * @param {Class}
     */
    OP3.Elements._extension.type.CartDownload = OP3.defineClass({

        Name: "OP3.Element.CartDownload",

        Extends: OP3.Elements._extension.type.Default,

        Constructor: function(arg) {
            return OP3.Elements._extension.type.Default.apply(this, arguments);
        },

        Prototype: {

            _type: "cartdownload",

            _props: function() {
                return [
                    [ OP3.Elements._extension.prop.ToggleStatusError, { label: OP3._("Edit Status Message") } ],

                    [ OP3.Elements._extension.prop.BoxModel ],
                    [ OP3.Elements._extension.prop.MarginTop ],
                    [ OP3.Elements._extension.prop.MarginBottom ],
                    [ OP3.Elements._extension.prop.MarginLeft ],
                    [ OP3.Elements._extension.prop.MarginRight ],
                    [ OP3.Elements._extension.prop.PaddingTop ],
                    [ OP3.Elements._extension.prop.PaddingBottom ],
                    [ OP3.Elements._extension.prop.PaddingLeft ],
                    [ OP3.Elements._extension.prop.PaddingRight ],
                    [ OP3.Elements._extension.prop.PaddingDrag ],
                    [ OP3.Elements._extension.prop.MarginAlign ],
                    [ OP3.Elements._extension.prop.MaxWidth ],

                    [ OP3.Elements._extension.prop.Display, { id: "displayDeviceVisibility" } ],
                    [ OP3.Elements._extension.prop.DeviceVisibility, { label: OP3._("Element Visible On") } ],
                    [ OP3.Elements._extension.prop.ForceVisibility ],

                    [ OP3.Elements._extension.prop.Id ],
                    [ OP3.Elements._extension.prop.Uuid ],
                    [ OP3.Elements._extension.prop.Caption ],
                    [ OP3.Elements._extension.prop.Class ],
                    [ OP3.Elements._extension.prop.LinkProperties ],
                    [ OP3.Elements._extension.prop.ZIndex ],
                    [ OP3.Elements._extension.prop.CodeBeforeElement ],
                    [ OP3.Elements._extension.prop.CodeAfterElement ],

                    // Link Properties - cartdownloaditem
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImageBase", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="base"]::before, .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "cartDownloadItemBackgroundColorBase", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="base"]::before, .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImage", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "cartDownloadItemBackgroundImageDisplay", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.Opacity, { id: "cartDownloadItemOpacity", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundPosition, { id: "cartDownloadItemBackgroundPosition", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundAttachment, { id: "cartDownloadItemBackgroundAttachment", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundRepeat, { id: "cartDownloadItemBackgroundRepeat", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundSize, { id: "cartDownloadItemBackgroundSize", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImageOverlay", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="overlay"]::before, .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "cartDownloadItemBackgroundColorOverlay", label: OP3._("Overlay Background Color"), selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="overlay"]::before, .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent [data-op3-border] > [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "cartDownloadItemBorderTopWidth", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "cartDownloadItemBorderTopStyle", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "cartDownloadItemBorderTopColor", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "cartDownloadItemBorderRightWidth", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "cartDownloadItemBorderRightStyle", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "cartDownloadItemBorderRightColor", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "cartDownloadItemBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "cartDownloadItemBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "cartDownloadItemBorderBottomColor", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "cartDownloadItemBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "cartDownloadItemBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "cartDownloadItemBorderLeftColor", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "cartDownloadItemBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "cartDownloadItemBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "cartDownloadItemBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "cartDownloadItemBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "cartDownloadItemBoxShadow", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "cartDownloadItemMarginTop", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "cartDownloadItemMarginBottom", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "cartDownloadItemMarginLeft", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "cartDownloadItemMarginRight", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "cartDownloadItemPaddingTop", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "cartDownloadItemPaddingBottom", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "cartDownloadItemPaddingLeft", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "cartDownloadItemPaddingRight", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "cartDownloadItemTransitionDuration", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"], .op3-element[data-op3-element-type="cartdownloaditem"] .op3-background-parent, .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border], .op3-element[data-op3-element-type="cartdownloaditem"] [data-op3-element-container] > [data-op3-border] > [data-op3-background]' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "cartDownloadItemBackgroundColorBaseHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background][data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImageBaseHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background][data-op3-background="base"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImageHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.Opacity, { id: "cartDownloadItemBackgroundOpacityHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundPosition, { id: "cartDownloadItemBackgroundPositionHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundAttachment, { id: "cartDownloadItemBackgroundAttachmentHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundRepeat, { id: "cartDownloadItemBackgroundRepeatHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundSize, { id: "cartDownloadItemBackgroundSizeHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background="image"]' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "cartDownloadItemBackgroundImageOverlayHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "cartDownloadItemBackgroundColorOverlayHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border] > [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "cartDownloadItemBorderTopWidthHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "cartDownloadItemBorderTopStyleHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "cartDownloadItemBorderTopColorHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "cartDownloadItemBorderRightWidthHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "cartDownloadItemBorderRightStyleHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "cartDownloadItemBorderRightColorHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "cartDownloadItemBorderBottomWidthHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "cartDownloadItemBorderBottomStyleHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "cartDownloadItemBorderBottomColorHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "cartDownloadItemBorderLeftWidthHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "cartDownloadItemBorderLeftStyleHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "cartDownloadItemBorderLeftColorHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container], .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "cartDownloadItemBorderTopLeftRadiusHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "cartDownloadItemBorderTopRightRadiusHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "cartDownloadItemBorderBottomRightRadiusHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "cartDownloadItemBorderBottomLeftRadiusHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "cartDownloadItemBoxShadowHover", selector: ' .op3-element[data-op3-element-type="cartdownloaditem"]:hover [data-op3-element-container] > [data-op3-border]' } ],

                    // Link Properties - name
                    [ OP3.Elements._extension.prop.FontFamily, { id: "nameFontFamily", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "nameColor", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "nameFontSize", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "nameLineHeight", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "nameLetterSpacing", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "nameFontWeight", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "nameFontStyle", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "nameTextTransform", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "nameTextDecoration", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "nameTextAlign", selector: '  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h1,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h2,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h3,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h4,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h5,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > h6,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > p,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > pre,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > blockquote,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ol,  .op3-element[data-op3-element-spec="name"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "nameBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "nameMarginTop", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "nameMarginBottom", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "nameMarginLeft", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "nameMarginRight", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "namePaddingTop", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "namePaddingBottom", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "namePaddingLeft", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "namePaddingRight", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "nameMaxWidth", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "nameBorderTopWidth", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "nameBorderTopStyle", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "nameBorderTopColor", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "nameBorderRightWidth", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "nameBorderRightStyle", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "nameBorderRightColor", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "nameBorderBottomWidth", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "nameBorderBottomStyle", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "nameBorderBottomColor", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "nameBorderLeftWidth", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "nameBorderLeftStyle", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "nameBorderLeftColor", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "nameBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "nameBorderTopRightRadius", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "nameBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "nameBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-spec="name"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "nameDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-spec="name"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "nameTransitionDuration", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "nameColorHover", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "nameFontWeightHover", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "nameFontStyleHover", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "nameTextTransformHover", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "nameTextDecorationHover", selector: ' .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="name"]:hover [data-op3-contenteditable] > ul' } ],

                    // Link Properties - description
                    [ OP3.Elements._extension.prop.FontFamily, { id: "descriptionFontFamily", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "descriptionColor", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "descriptionFontSize", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "descriptionLineHeight", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "descriptionLetterSpacing", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "descriptionFontWeight", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "descriptionFontStyle", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "descriptionTextTransform", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "descriptionTextDecoration", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "descriptionTextAlign", selector: ' .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"] [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "descriptionBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "descriptionMarginTop", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "descriptionMarginBottom", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "descriptionMarginLeft", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "descriptionMarginRight", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "descriptionPaddingTop", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "descriptionPaddingBottom", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "descriptionPaddingLeft", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "descriptionPaddingRight", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "descriptionMaxWidth", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "descriptionBorderTopWidth", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "descriptionBorderTopStyle", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "descriptionBorderTopColor", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "descriptionBorderRightWidth", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "descriptionBorderRightStyle", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "descriptionBorderRightColor", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "descriptionBorderBottomWidth", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "descriptionBorderBottomStyle", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "descriptionBorderBottomColor", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "descriptionBorderLeftWidth", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "descriptionBorderLeftStyle", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "descriptionBorderLeftColor", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "descriptionBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "descriptionBorderTopRightRadius", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "descriptionBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "descriptionBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-spec="description"] .op3-text-wrapper' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "descriptionDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-spec="description"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "descriptionTransitionDuration", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "descriptionColorHover", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "descriptionFontWeightHover", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "descriptionFontStyleHover", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "descriptionTextTransformHover", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "descriptionTextDecorationHover", selector: ' .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h1, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h2, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h3, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h4, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h5, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > h6, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > p, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > pre, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > blockquote, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ol, .op3-element[data-op3-element-spec="description"]:hover [data-op3-contenteditable] > ul' } ],

                    // Link Properties - button
                    [ OP3.Elements._extension.prop.Color, { id: "buttonColor", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MaxWidth, { id: "buttonMaxWidth", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.Height, { id: "buttonHeight", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "buttonBackgroundImageOverlay", selector: ' .op3-element[data-op3-element-type="button"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-type="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "buttonBackgroundColorOverlay", selector: ' .op3-element[data-op3-element-type="button"] [data-op3-background="overlay"]::before, .op3-element[data-op3-element-type="button"] [data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.FontFamily, { id: "buttonFontFamily", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonFontSize", selector: ' .op3-element[data-op3-element-type="button"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LineHeight, { id: "buttonLineHeight", selector: ' .op3-element[data-op3-element-type="button"] > a .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "buttonLetterSpacing", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "buttonFontWeight", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "buttonFontStyle", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "buttonTextTransform", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "buttonTextDecoration", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.AlignItems, { id: "buttonButtonAlignText", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.TextAlign, { id: "buttonButtonTextAlign", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonSubtextDisplay", selector: ' .op3-element[data-op3-element-type="button"] .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontWeight, { id: "buttonFontWeightSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontStyle, { id: "buttonFontStyleSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextTransform, { id: "buttonTextTransformSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.TextDecoration, { id: "buttonTextDecorationSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonFontSizeSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.LetterSpacing, { id: "buttonLetterSpacingSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonOffsetXSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "buttonOffsetYSubtext", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-subtext' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonDisplay", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon, .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.Op3Icon, { id: "buttonOp3Icon", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonIconColor", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FontSize, { id: "buttonIconSize", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.FlexDirection, { id: "buttonIconDirection", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container' } ],
                    [ OP3.Elements._extension.prop.Width, { id: "buttonIconSpacing", selector: ' .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-divider' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "buttonBorderTopWidth", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "buttonBorderTopStyle", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "buttonBorderTopColor", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "buttonBorderRightWidth", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "buttonBorderRightStyle", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "buttonBorderRightColor", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "buttonBorderBottomWidth", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "buttonBorderBottomStyle", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "buttonBorderBottomColor", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "buttonBorderLeftWidth", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "buttonBorderLeftStyle", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "buttonBorderLeftColor", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "buttonBorderTopLeftRadius", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "buttonBorderTopRightRadius", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "buttonBorderBottomRightRadius", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "buttonBorderBottomLeftRadius", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadow", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadowInset", selector: ' .op3-element[data-op3-element-type="button"] > a [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.TextShadow, { id: "buttonTextShadow", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginTop, { id: "buttonMarginTop", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginBottom, { id: "buttonMarginBottom", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonMarginLeft", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "buttonMarginRight", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.PaddingTop, { id: "buttonPaddingTop", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingBottom, { id: "buttonPaddingBottom", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingLeft, { id: "buttonPaddingLeft", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.PaddingRight, { id: "buttonPaddingRight", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginLeft, { id: "buttonHorizontalSpacingLeft", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.MarginRight, { id: "buttonHorizontalSpacingRight", selector: ' .op3-element[data-op3-element-type="button"] > a' } ],
                    [ OP3.Elements._extension.prop.Display, { id: "buttonDisplayDeviceVisibility", selector: ' .op3-element[data-op3-element-type="button"]' } ],
                    [ OP3.Elements._extension.prop.TransitionDuration, { id: "buttonTransitionDuration", selector: ' .op3-element[data-op3-element-type="button"] > a, .op3-element[data-op3-element-type="button"] > a > .op3-text-container > .op3-icon' } ],
                    [ OP3.Elements._extension.prop.Filter, { id: "buttonFilterHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonColorHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.Color, { id: "buttonIconColorHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover > .op3-text-container > i' } ],
                    [ OP3.Elements._extension.prop.BackgroundImage, { id: "buttonBackgroundImageOverlayHover", selector: ' .op3-element[data-op3-element-type="button"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BackgroundColor, { id: "buttonBackgroundColorOverlayHover", selector: ' .op3-element[data-op3-element-type="button"] [data-op3-background][data-op3-background="overlay"]::after' } ],
                    [ OP3.Elements._extension.prop.BorderTopWidth, { id: "buttonBorderTopWidthHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopStyle, { id: "buttonBorderTopStyleHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopColor, { id: "buttonBorderTopColorHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightWidth, { id: "buttonBorderRightWidthHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightStyle, { id: "buttonBorderRightStyleHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderRightColor, { id: "buttonBorderRightColorHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomWidth, { id: "buttonBorderBottomWidthHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomStyle, { id: "buttonBorderBottomStyleHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderBottomColor, { id: "buttonBorderBottomColorHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftWidth, { id: "buttonBorderLeftWidthHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftStyle, { id: "buttonBorderLeftStyleHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderLeftColor, { id: "buttonBorderLeftColorHover" , selector: ' .op3-element[data-op3-element-type="button"] > a:hover [data-op3-border]' } ],
                    [ OP3.Elements._extension.prop.BorderTopLeftRadius, { id: "buttonBorderTopLeftRadiusHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderTopRightRadius, { id: "buttonBorderTopRightRadiusHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomRightRadius, { id: "buttonBorderBottomRightRadiusHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BorderBottomLeftRadius, { id: "buttonBorderBottomLeftRadiusHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],
                    [ OP3.Elements._extension.prop.BoxShadow, { id: "buttonBoxShadowHover", selector: ' .op3-element[data-op3-element-type="button"] > a:hover' } ],

                ];
            },
        },

    });

    // Disable ice editor in LiveEditor
    // on text (name, description)
    OP3.bind("ready elementappend", function(e, o) {
        var parent = "cartdownload",
            children = [
                '.op3-element[data-op3-element-spec="name"] [data-op3-contenteditable]',
                '.op3-element[data-op3-element-spec="description"] [data-op3-contenteditable]',
                '.op3-element[data-op3-element-spec="togglestatuserror"] [data-op3-contenteditable]',
            ],
            element = OP3.$(null);
        if (o && o.node)
            element = OP3.$(o.node);
        else
            element = OP3.$(parent);
        if (element.type() !== parent)
            element = element.find(parent);

        // no need to edit values
        // will be handled by opc plugin on frontend
        element
            .jq()
            .find(children.join(","))
            .each(function() {
               if (this.ice)
                    this.ice.destroy();
            });
    });

    // Sync button contenteditable
    var _recursion = false;
    OP3.bind("elementchange::button::html elementchange::button::html2", function(e, o) {
        if (_recursion || o.historyPending)
            return;
        _recursion = true;

        OP3.$(o.node)
            .closest("cartdownload")
            .find("button")
            .not(o.node)
            .setOption(o.id, o.value.after, "all");

        _recursion = false;
    });

})(jQuery, window, document);
